options:
  search_path:
    type: string
    default: "/data"
    description: |
      Path to search in. Defaults to the charm's data storage location.
      Can be overridden using 'juju config ripgrep-operator search_path=<path>'
  max_results:
    type: int
    default: 1000
    description: "Maximum number of search results to return"
  default_context_lines:
    type: int
    default: 2
    description: "Number of context lines to show around matches" 