#!/bin/bash

# Change to the charm directory
cd "$(dirname "$0")"

# Set up Python environment
VENV_DIR=".venv"
if [ ! -d "$VENV_DIR" ]; then
    python3 -m venv "$VENV_DIR"
    # "$VENV_DIR/bin/pip" install -r requirements.txt
fi

# Activate virtual environment
. "$VENV_DIR/bin/activate"

# TODO: Resolve by installing 'pip' first and then requirements.txt
# "$VENV_DIR/bin/pip" install -r requirements.txt

# Run the charm
PYTHONPATH=. exec python3 -m src.charm.charm "$@"