version: '3.8'

services:
  ripgrep-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ripgrep-dev
    hostname: ripgrep-dev
    privileged: true  # Required for systemd and LXD
    security_opt:
      - seccomp:unconfined  # Required for nested containers
      - apparmor:unconfined
    volumes:
      - ../..:/workspace/ripgrep-operator:cached
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /lib/modules:/lib/modules:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    environment:
      - TERM=xterm-256color
      - SNAP_COMMON=/var/snap/common
    networks:
      - ripgrep-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: unless-stopped

networks:
  ripgrep-net:
    name: ripgrep-net
    driver: bridge
