version: '3.8'

services:
  ripgrep-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ripgrep-dev
    hostname: ripgrep-dev
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ../..:/workspace/ripgrep-operator:cached
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /lib/modules:/lib/modules:ro
      - /var/lib/snapd:/var/lib/snapd:rw
      - /snap:/snap:rw
      - snapdata:/var/snap
    tmpfs:
      - /tmp:exec,mode=1777
      - /run:exec,mode=1777
      - /run/lock:exec,mode=1777
      - /run/snapd.socket
    environment:
      - TERM=xterm-256color
      - SNAP_COMMON=/var/snap/common
      - container=docker
    networks:
      - ripgrep-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - SYS_TIME
      - SYS_RESOURCE
      - SYS_MODULE
      - MKNOD
    devices:
      - /dev/fuse

networks:
  ripgrep-net:
    name: ripgrep-net
    driver: bridge

volumes:
  snapdata:
