#cloud-config

# System update and upgrade
package_update: true
package_upgrade: true

# Install required packages
packages:
  - build-essential
  - python3-pip
  - python3-dev
  - git
  - curl
  - wget

# Configure snap packages
snap:
  commands:
    # Install required snaps
    - snap install lxd
    - snap install juju --classic
    - snap install charmcraft --classic

# Create default user with sudo access
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    lock_passwd: true

# Run commands after system is set up
runcmd:
  # Initialize LXD
  - [lxd, init, --auto]
  
  # Configure git
  - [su, ubuntu, -c, "git config --global init.defaultBranch main"]
  
  # Create development directory
  - [mkdir, -p, /home/ubuntu/ripgrep-operator]
  - [chown, -R, ubuntu:ubuntu, /home/ubuntu/ripgrep-operator]

# Write message to indicate setup completion
final_message: "The system is finally up, after $UPTIME seconds"

# Power settings - don't power off on lid close
power_state:
  mode: reboot
  timeout: 30
  condition: True
